
ABACUS_API_KEY = "s2_7ec8cf43a89443bf91d9954336134bf0"
MODEL_NAME = "gemini-2.5-pro"


SHEETS_FOLDER_ID = "1VyxfRqAeh4ecCow3Rm4rQi_BWRD_Ss9G"
SHEET_RANGE = "A:Z"
SHEETS_IDS = "" 

[google_service_account]
type = "service_account"
project_id = "chatbotaula17"
private_key_id = "fddef514a2e4ac16bd01c5639eaa2d07d96b17fd"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDDTBAMkLWPBoH2
T+dxXphgda5J0DnLeUosERtbeUcllGSM+tuDXRlR7io49+roOqGwqqwFrWLKgqjo
+YtRo1zDalymelMMQaIhtoSR0gC6SFUcp3vWSA09v+D2aXClDFYkEToGf2IXBCsi
4NP07QmJYf+gprXNVbNUS1APhs0UrxkEHGGPVyHW+wM3zsXKAlmVrYV8T1i5e6AU
XVPrIsoR1fmSC3jL6nUEABRzEgjjL0Z60NjxHqzbgS9yiNrHAunDUi6+qH6i9/wF
sak3hVeenqlb2Vya2ShjVqMhd3+jzNl+S5J0nWlxVVwBtGBP32UI3obDXf1zypgy
kJTADd0nAgMBAAECggEADhTudVF73ee8uDtztz94YkAqBIWAnVTODdZf8B0TDbkg
9O9jo5mzaS5wmfH6XKtZnEj6JWCmpm58amwP6R+L4UVKj/BzC4ex/pdQAMmxJr1v
caT772v7lG/A81OP/T6h+XDKi8xkkL9KsvWeIuNylBbeXUGYC0m6KAJUMAJqyCpl
to1XZHeEHYP5oHKNN8Hiu/x8Cu2JQqupt5G6AjghMXFNFzeWs95j5pmFPaLVXvno
sAgArP1zztTfGJ2Mhqci/W/NiedFvkUeWuL+KpLNXdBFuhEizoOtY6V5gJwMenWV
eGzwu0hhx+Zxu8uMBoL0+Y32RkUj9DhAkTcff64F/QKBgQDiKkNoyYoVLdLzP2NH
mGiLgCYpDbcxQAPs6RPbM4DzDQd4IwO9GRRZUpaisBjdRJko9/QQhyajx7fgKpey
JOEjHMcAw+38UnET2l8Q18V5DPWX6v+fZhihmeq3QAX4isV+8Xf6ZuSl6d9BlDGf
sBJJU8wVmPeLr9EoHd3IwurlhQKBgQDdD15g7tDWUobw0w6hJXy9tA69oA0UNFGD
X/lzvHko7RsUN7VrfvyVld5cYaU6JgGyP+SSnpCnrxEfGARiBRls6DbHEH1dlQmm
RB2VOnPI+Wxq/9nF5JM9/HzzfM/r42uGify7EKsG9e/19KIMOJmym9t9211bq4fY
nJWBDK7xuwKBgFucyQ+CS/fGRyQXcizHNNoFP+/zSVie2Lg3tb5eP4a0qWjlrhcE
OLTx+mjOMlQ2/F+XCPtE88b2GKqqNiaIP9ZMSuQpeZZzArELDOUysiAVusod/Avi
fGnBgk1WltSVyehhAbuhwE7gzHmxAOTxmoavdgTtoKCpyGyapIM1SZdNAoGAJJ4v
HA9zOI1jHPFZMwhqqWHyLyccA4THG+QCBlHqIAVmvuqbersGTCEPPG5QWFmDXmuH
CWKKw7wUMfpgf3wowgmVSVRJ7/6IIqqV2+pa06e9ddv7zvQWD+aLLCo4pvJ9FUQ2
QSZ5riV/IlbroOqfSx7WNPrpdA3t6svFWCMpt5ECgYEAsJmN66mnPWSSQBUk5mMw
GDGUc9cyhCvdzuGMH88JS56MER84rFRCKPrBQfQVlnT/xrEcARfM18bGo70QBRG8
udUDjPm8M2/WKSF8uYydZTnngdPSXU06YFMBQWmxP5esvPVGgIKOUAIs308Ju21U
jY90tCoqiE3bmgxIbmD01qw=
-----END PRIVATE KEY-----"""
client_email = "sheets-reader@chatbotaula17.iam.gserviceaccount.com"
client_id = "117193447779719276268"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-reader@chatbotaula17.iam.gserviceaccount.com"
universe_domain = "googleapis.com"


GOOGLE_SERVICE_ACCOUNT_CREDENTIALS = """
{
  "type": "service_account",
  "project_id": "chatbotaula17",
  "private_key_id": "fddef514a2e4ac16bd01c5639eaa2d07d96b17fd",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDDTBAMkLWPBoH2\\nT+dxXphgda5J0DnLeUosERtbeUcllGSM+tuDXRlR7io49+roOqGwqqwFrWLKgqjo\\n+YtRo1zDalymelMMQaIhtoSR0gC6SFUcp3vWSA09v+D2aXClDFYkEToGf2IXBCsi\\n4NP07QmJYf+gprXNVbNUS1APhs0UrxkEHGGPVyHW+wM3zsXKAlmVrYV8T1i5e6AU\\nXVPrIsoR1fmSC3jL6nUEABRzEgjjL0Z60NjxHqzbgS9yiNrHAunDUi6+qH6i9/wF\\nsak3hVeenqlb2Vya2ShjVqMhd3+jzNl+S5J0nWlxVVwBtGBP32UI3obDXf1zypgy\\nkJTADd0nAgMBAAECggEADhTudVF73ee8uDtztz94YkAqBIWAnVTODdZf8B0TDbkg\\n9O9jo5mzaS5wmfH6XKtZnEj6JWCmpm58amwP6R+L4UVKj/BzC4ex/pdQAMmxJr1v\\ncaT772v7lG/A81OP/T6h+XDKi8xkkL9KsvWeIuNylBbeXUGYC0m6KAJUMAJqyCpl\\nto1XZHeEHYP5oHKNN8Hiu/x8Cu2JQqupt5G6AjghMXFNFzeWs95j5pmFPaLVXvno\\nsAgArP1zztTfGJ2Mhqci/W/NiedFvkUeWuL+KpLNXdBFuhEizoOtY6V5gJwMenWV\\neGzwu0hhx+Zxu8uMBoL0+Y32RkUj9DhAkTcff64F/QKBgQDiKkNoyYoVLdLzP2NH\\nmGiLgCYpDbcxQAPs6RPbM4DzDQd4IwO9GRRZUpaisBjdRJko9/QQhyajx7fgKpey\\nJOEjHMcAw+38UnET2l8Q18V5DPWX6v+fZhihmeq3QAX4isV+8Xf6ZuSl6d9BlDGf\\nsBJJU8wVmPeLr9EoHd3IwurlhQKBgQDdD15g7tDWUobw0w6hJXy9tA69oA0UNFGD\\nX/lzvHko7RsUN7VrfvyVld5cYaU6JgGyP+SSnpCnrxEfGARiBRls6DbHEH1dlQmm\\nRB2VOnPI+Wxq/9nF5JM9/HzzfM/r42uGify7EKsG9e/19KIMOJmym9t9211bq4fY\\nnJWBDK7xuwKBgFucyQ+CS/fGRyQXcizHNNoFP+/zSVie2Lg3tb5eP4a0qWjlrhcE\\nOLTx+mjOMlQ2/F+XCPtE88b2GKqqNiaIP9ZMSuQpeZZzArELDOUysiAVusod/Avi\\nfGnBgk1WltSVyehhAbuhwE7gzHmxAOTxmoavdgTtoKCpyGyapIM1SZdNAoGAJJ4v\\nHA9zOI1jHPFZMwhqqWHyLyccA4THG+QCBlHqIAVmvuqbersGTCEPPG5QWFmDXmuH\\nCWKKw7wUMfpgf3wowgmVSVRJ7/6IIqqV2+pa06e9ddv7zvQWD+aLLCo4pvJ9FUQ2\\nQSZ5riV/IlbroOqfSx7WNPrpdA3t6svFWCMpt5ECgYEAsJmN66mnPWSSQBUk5mMw\\nGDGUc9cyhCvdzuGMH88JS56MER84rFRCKPrBQfQVlnT/xrEcARfM18bGo70QBRG8\\nudUDjPm8M2/WKSF8uYydZTnngdPSXU06YFMBQWmxP5esvPVGgIKOUAIs308Ju21U\\njY90tCoqiE3bmgxIbmD01qw=\\n-----END PRIVATE KEY-----",
  "client_email": "sheets-reader@chatbotaula17.iam.gserviceaccount.com",
  "client_id": "117193447779719276268",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sheets-reader%40chatbotaula17.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
